### ISSUE TITLE
UI improvement suggestion

### ISSUE THREAD

**Issue by drupchen** [buda-base/pecha-printer#3]
The Save button is somehow misleading: what it does is to process the input pdf and write it to file.
Something like "Generate print-ready" or "Process input" might be better???

Also, the current behaviour is to close de window as soon as one file is processed. Imagining someone has a small bunch of files to process, it becomes annoying to have to run the project at each file instead of having a "Finished! Do you want to process another file?" option or something like this.

**Comment by ngawangtrinley** [comment]
solved
